### ISSUE TITLE
Convert to cookiecutter

### ISSUE THREAD

**Issue by seerwright** [Justintime50/python-template#1]
### Convert to cookiecutter

**Suggestion:** since this is a template, consider using the Cookiecutter templating scheme that will enable users to easily customize your template to their needs. The current Github template works, too, and perhaps that's your preference after thoughtful deliberation. If so, disregard. Thanks for this repo!

https://github.com/cookiecutter/cookiecutter

Edit: clarifying that this is already a template for Github templating.

**Comment by Justintime50** [comment]
Hey @seerwright thanks for the suggestion! I checked it out (haven't used it before) and think it's an interesting concept; however, I don't know if I want to add a bunch of overhead to the project. What's the main benefit of incorporating cookiecutter vs not?

**Comment by Justintime50** [comment]
After looking into this more, I've decided against integrating with CookieCutter, it's a bit more overhead than I'd like for this project. I did however revisit all the instructions and easy text-replacements and clarified those and made them more uniform to assist with getting started with this template, should be a bit more straightforward now.

Thanks again for the suggestion!
